# Generated by Django 4.2.6 on 2023-11-23 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_version'),
    ]

    operations = [
    ]
